INSERT INTO fruit(id, name, color) VALUES (1, 'Cherry', 'Red');
INSERT INTO fruit(id, name, color) VALUES (2, 'Apple', 'Red');
INSERT INTO fruit(id, name, color) VALUES (3, 'Banana', 'Yellow');
INSERT INTO fruit(id, name, color) VALUES (4, 'Avocado', 'Green');
INSERT INTO fruit(id, name, color) VALUES (5, 'Strawberry', 'Red');


DROP TABLE IF EXISTS job;
CREATE TABLE job (
                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                     title VARCHAR(255),
                     location VARCHAR(255),
                     salary DOUBLE,
                     jobType VARCHAR(255),
                     postedAt TIMESTAMP
);

-- H2 specific syntax for subtracting interval from timestamp
INSERT INTO job(title, location, salary, jobType, postedAt)
VALUES ('Software Engineer', 'New York', 120000, 'Full-time', DATEADD('DAY', 1, NOW()));

INSERT INTO job(title, location, salary, jobType, postedAt)
VALUES ('Data Scientist', 'San Francisco', 150000, 'Full-time',DATEADD('DAY', 2, NOW()));

INSERT INTO job(title, location, salary, jobType, postedAt)
VALUES ('Product Manager', 'New York', 130000, 'Full-time', DATEADD('DAY', 3, NOW()));

INSERT INTO job(title, location, salary, jobType, postedAt)
VALUES ('Designer', 'Los Angeles', 90000, 'Part-time', DATEADD('DAY', -4, NOW()));